# version: "3.9"

# services:
#   todo-list:
#     image: diamol/ch09-todo-list
#     ports:
#       - "8050:80"
#     networks:
#       - app-net

#   prometheus:
#     build: 
#       context: ./prometheus
#       dockerfile: Dockerfile
#     ports:
#       - "9090:9090"
#     networks:
#       - app-net

#   grafana:
#     build: 
#       context: ./grafana
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - prometheus
#     networks:
#       - app-net

# networks:
#   app-net:
#       name: nat
version: "3.9"

services:
  todo-list:
    image: diamol/ch09-todo-list
    ports:
      - "8050:80"
    networks:
      - app-net

  prometheus:
    image: mmiotkug/prometheus-image:1.0
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: diamol/ch09-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net:
      name: nat